pipeline {
    agent any

    environment {
        CI = 'true'
        // Mot de passe pour le repository Nexus
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build and Package') {
            steps {
                sh 'npm run build'
                sh 'tar -zcvf my-react-app.tar.gz build/'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
   
        stage('Deploy to Nexus') {
            steps {
                script {
                    def componentsPath = "${env.WORKSPACE}/my-react-app.tar.gz"
                    def nexusUrl = 'http://localhost:8081'
                    def nexusUsername = 'admin'
                    def nexusPassword = 'hamza'
                    def nexusRepository = 'hamza'
                    sh "curl -u ${nexusUsername}:${nexusPassword} --upload-file ${componentsPath} http://localhost:8081/repository/hamza/"
                    sh "cd ${componentsPath} && curl -u ${nexusUsername}:${nexusPassword} --upload-file ./* http://localhost:8081/repository/hamza/"
                    sh "curl -u admin:hamza --upload-file my-react-app.tar.gz ${nexusUrl}/repository/${nexusRepository}/my-react-app.tar.gz"
                    sh "npm config set registry http://localhost:8081/repository/hamza/"
                    sh "npm login --registry=${nexusUrl}/repository/${nexusRepository} --user=${nexusUsername} --password=${nexusPassword}"
                    sh "npm publish"
                }
            }
        }
    }
}
