pipeline {
    agent any

    environment {
        CI = 'true'
        NEXUS_URL = 'http://localhost:8081' // URL de votre instance Nexus
        NEXUS_REPO_ID = 'hamza' // ID de votre repository Nexus
        NEXUS_REPO_USERNAME = 'hamza' // Nom d'utilisateur pour le repository Nexus
        NEXUS_REPO_PASSWORD = 'hamza' // Mot de passe pour le repository Nexus
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/username/my-react-app.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build and Package') {
            steps {
                sh 'npm run build'
                sh 'tar -zcvf my-react-app.tar.gz build/'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Avez-vous terminé d\'utiliser le site web? (Cliquez sur "Proceed" pour continuer)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy to Nexus') {
            steps {
                sh "curl -v -u ${NEXUS_REPO_USERNAME}:${NEXUS_REPO_PASSWORD} --upload-file my-react-app.tar.gz ${NEXUS_URL}/repository/${NEXUS_REPO_ID}/my-react-app.tar.gz"
            }
        }
    }
}
